import nibabel as nib
import numpy as np
import os
import pandas as pd
from PIL import Image
from tqdm import tqdm

# ── Config ───────────────────────────────────────────────
BASE_DIR   = r'D:\Projects\Dissertation\Dataset'
CSV_PATH   = r'D:\Projects\Dissertation\Dataset\CSV File with Demographic and Clinical Data.xlsx'
OUTPUT_DIR = r'D:\Projects\Dissertation\Dataset\OASIS_slices_CORONAL'
IMG_SIZE   = 128

DISC_DIRS = [
    os.path.join(BASE_DIR, f'oasis_cross-sectional_disc{i}')
    for i in range(1, 13)
]

# ── Orientation selection ─────────────────────────────────
# ORIENTATION options: 'axial', 'coronal', 'sagittal'            # two-dimensional views of MRI scans

ORIENTATION = 'coronal'
LANDMARK    = 'anterior_hippocampal'   # best for AD 
# ────────────────────────────────────────────────────────


""" OASIS-1 data is ALREADY registered to T88 atlas space
This means fixed indices map to the SAME anatomy in ALL subjects
Data shape: (176, 208, 176)
x=176 (left-right), y=208 (ant-post), z=176 (inf-sup)"""


# ── CORONAL landmark ranges (data[:, y, :]) ─────────────
# y increases posterior → anterior in T88 space
# Hippocampus is in mid-posterior region ≈ y=95-130

# Skeleton code to extract 2D slices generated by Gemini and was modified manually 
# prompt: python code to extract 2D Coronal brain MRI slices (T88 atlas space OASIS-1 dataset) from given landmarks and their ranges for identifying AD"""

CORONAL_LANDMARKS = {
     # Gold standard for AD: hippocampal head, optic chiasm level
     'anterior_hippocampal': range(95, 115, 3),

     # Hippocampal body + collateral sulcus
     'posterior_hippocampal': range(115, 133, 3),

     # Full hippocampal slab — most comprehensive
     'full_hippocampal': range(95, 133, 3),
}
def get_slice_indices():

   if ORIENTATION == 'coronal':
         return CORONAL_LANDMARKS[LANDMARK]
   else:
        raise ValueError(f"Unknown orientation: {ORIENTATION}")


def extract_slice(data, orientation, idx):
    """Extract a single 2D slice from 3D volume."""    
    if orientation == 'coronal':
        return data[:, idx, :]        # shape (176, 176)


def is_quality_slice(slice_2d, min_mean=10, min_nonzero=0.08,
                     max_nonzero=0.92, min_std=8):
    """  Quality filters — returns True if slice passes all checks. # filter partially generated by gpt

    Filters:
    - min_mean:     skip near-black slices
    - min_nonzero:  skip mostly empty slices
    - max_nonzero:  skip edge artifact slices
    - min_std:      skip very low contrast / flat slices """

    if slice_2d.mean()                              < min_mean:     return False
    if np.count_nonzero(slice_2d) / slice_2d.size  < min_nonzero:  return False
    if np.count_nonzero(slice_2d) / slice_2d.size  > max_nonzero:  return False
    if slice_2d.std()                               < min_std:      return False
    return True

# Main fuction (extraction process) partially genered by Gemini (improvising the prompt from line:38)
def main():
    print(f"Orientation : {ORIENTATION.upper()}")
    print(f"Landmark    : {LANDMARK}")
    print(f"Slice range : {list(get_slice_indices())}\n")

    # Load clinical labels
    df = pd.read_excel(CSV_PATH)
    df['label'] = df['CDR'].apply(
        lambda x: 'alzheimers' if x > 0 else 'healthy'
    )

    out_healthy = os.path.join(OUTPUT_DIR, 'healthy')
    out_alz     = os.path.join(OUTPUT_DIR, 'alzheimers')
    os.makedirs(out_healthy, exist_ok=True)
    os.makedirs(out_alz,     exist_ok=True)

    processed    = 0
    skipped      = 0
    total_slices = 0

    for disc_dir in DISC_DIRS:
        if not os.path.exists(disc_dir):
            print(f"⚠️  Skipping missing: {os.path.basename(disc_dir)}")
            continue

        print(f"Processing: {os.path.basename(disc_dir)}")

        subject_folders = sorted([
            f for f in os.listdir(disc_dir)
            if f.startswith('OAS1_') and
            os.path.isdir(os.path.join(disc_dir, f))
        ])

        for subject in tqdm(subject_folders):
            subject_id = subject.strip()

            match = df[df['ID'] == subject_id]
            if match.empty:
                skipped += 1
                continue

            label   = match.iloc[0]['label']
            out_dir = out_healthy if label == 'healthy' else out_alz

            # Find masked brain image
            img_file = None
            for root, dirs, files in os.walk(
                os.path.join(disc_dir, subject)
            ):
                for f in files:
                    if f.endswith('_t88_masked_gfc.img'):
                        img_file = os.path.join(root, f)
                        break
                if img_file:
                    break

            if img_file is None:
                skipped += 1
                continue

            try:
                img  = nib.load(img_file)
                data = img.get_fdata(dtype=np.float32)
                data = np.squeeze(data)

                # Normalise to 0-255
                data = (data - data.min()) / (
                    data.max() - data.min() + 1e-8
                ) * 255
                data = data.astype(np.uint8)

                saved = 0
                for i, idx in enumerate(get_slice_indices()):

                    slice_2d = extract_slice(data, ORIENTATION, idx)

                    if not is_quality_slice(slice_2d):
                        continue

                    pil_img  = Image.fromarray(slice_2d).resize(
                        (IMG_SIZE, IMG_SIZE), Image.LANCZOS
                    )
                    fname    = (
                        f'{subject_id}_{ORIENTATION}'
                        f'_{LANDMARK}_idx{idx:03d}.png'
                    )
                    pil_img.save(os.path.join(out_dir, fname))
                    saved += 1

                if saved > 0:
                    processed    += 1
                    total_slices += saved
                else:
                    skipped += 1

            except Exception as e:
                print(f"  ❌ {subject}: {e}")
                skipped += 1

    # Summary
    h = len(os.listdir(out_healthy))
    a = len(os.listdir(out_alz))
    print(f"\n{'='*45}")
    print(f"✅  Done — {ORIENTATION.upper()} / {LANDMARK}")
    print(f"Processed : {processed} | Skipped: {skipped}")
    print(f"Healthy   : {h}")
    print(f"Alzheimer : {a}")
    print(f"Total     : {h + a}")
    print(f"{'='*45}")


if __name__ == '__main__':
    main()